export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
<<<<<<< HEAD
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const SAVE_ACCOUNT_SESSION = 'SAVE_ACCOUNT_SESSION';
=======
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
>>>>>>> 960a83c (commit)
